"use client";
import { useRef, useState } from "react";
import type { ChallengeAttempt, JsonValue, NodeChallengeProgress } from "@/lib/types";
import { SOFTWARE_SCENARIOS, evaluateSoftware } from "@/lib/challenges/software/engine";
import type { SoftwareChallengeNodeId } from "@/lib/challenges/software/registry";
interface Props { nodeId: SoftwareChallengeNodeId; savedProgress?: NodeChallengeProgress; readOnly: boolean; onSave: (progress: NodeChallengeProgress) => void; onComplete: (progress: NodeChallengeProgress) => void; }
const STATES = ["objeto detectado", "objeto al alcance", "objeto tomado", "base detectada", "batería baja"];
const ARCH = { camera: ["detector", "planner", "motores"], detector: ["planner", "controlador", "motores"], planner: ["controlador", "detector", "motores"], controlador: ["motores", "planner", "detector"] };
export function SoftwareChallenge({ nodeId, savedProgress, readOnly, onSave, onComplete }: Props) {
  const scenario = SOFTWARE_SCENARIOS[nodeId]; const [progress, setProgress] = useState(() => initialProgress(nodeId, savedProgress)); const [feedback, setFeedback] = useState(""); const openedAt = useRef(progress.updatedAt); const step = progress.steps.mission; const completed = Boolean(progress.completedAt);
  const update = (draft: JsonValue) => { if (readOnly || completed) return; const next = { ...progress, updatedAt: Date.now(), steps: { mission: { ...step, draft } } }; setProgress(next); onSave(next); };
  const hint = () => { if (readOnly || completed || step.revealedHints >= 3) return; const next = { ...progress, updatedAt: Date.now(), steps: { mission: { ...step, revealedHints: step.revealedHints + 1 } } }; setProgress(next); onSave(next); };
  const submit = () => { if (readOnly || completed) return; const result = evaluateSoftware(nodeId, step.draft); const now = Date.now(); const attempt: ChallengeAttempt = { id: crypto.randomUUID(), nodeId, stepId: "mission", attemptNumber: step.attempts.length + 1, startedAt: openedAt.current, submittedAt: now, durationSeconds: Math.max(0, Math.round((now - openedAt.current) / 1000)), answer: step.draft, isCorrect: result.correct, hintsUsed: step.revealedHints, metadata: { evaluator: nodeId === "S4" ? "human" : "local" } }; const next = { ...progress, updatedAt: now, completedAt: result.correct ? now : null, steps: { mission: { ...step, attempts: [...step.attempts, attempt], solvedAt: result.correct ? now : null } }, analytics: { ...progress.analytics, attempts: step.attempts.length + 1, lastEvent: result.correct ? "completed" : "failed_test" } }; setProgress(next); onSave(next); if (result.correct) onComplete(next); setFeedback(result.feedback); openedAt.current = now; };
  return <div className="mx-auto grid max-w-6xl gap-5 lg:grid-cols-[19rem_minmax(0,1fr)]"><aside className="rounded-2xl border border-[#7B7FE8]/25 bg-[#101432] p-5"><span className="rounded-full border border-[#7B7FE8]/35 bg-[#7B7FE8]/10 px-3 py-1 text-[10px] font-semibold uppercase tracking-[0.12em] text-[#b8baff]">{scenario.category}</span><h2 id="skill-detail-title" className="mt-5 font-heading text-2xl font-semibold text-ink">{scenario.title}</h2><p id="skill-detail-description" className="mt-3 text-sm leading-6 text-muted">{scenario.objective}</p><button type="button" onClick={hint} disabled={readOnly || completed || step.revealedHints >= 3} className="mt-6 min-h-10 rounded-lg border border-[#7B7FE8]/35 px-4 text-xs font-semibold text-[#b8baff] disabled:opacity-40">Pista {Math.min(3, step.revealedHints + 1)} de 3</button>{step.revealedHints > 0 && <ol className="mt-4 space-y-2">{scenario.hints.slice(0, step.revealedHints).map((item, index) => <li key={item} className="text-xs leading-5 text-ice"><span className="mr-2 text-[#b8baff]">{index + 1}.</span>{item}</li>)}</ol>}<p className={`mt-5 text-xs leading-5 ${completed ? "text-ok" : "text-muted"}`} aria-live="polite">{feedback || (completed ? "Reto completado." : `${step.attempts.length} intentos registrados`)}</p></aside><main className="rounded-2xl border border-line bg-[#06131e] p-4 sm:p-6"><Mission nodeId={nodeId} draft={step.draft} disabled={readOnly || completed} onChange={update} /><div className="mt-5 flex items-center justify-between border-t border-line pt-4"><span className="text-xs text-muted">Tests locales · intentos ilimitados</span><button type="button" onClick={submit} disabled={readOnly || completed} className="min-h-11 rounded-lg bg-[#7B7FE8] px-5 text-sm font-semibold text-white disabled:opacity-50">{nodeId === "S4" ? "Entregar propuesta" : "Ejecutar tests"}</button></div></main></div>;
}
function Mission({ nodeId, draft, disabled, onChange }: { nodeId: SoftwareChallengeNodeId; draft: JsonValue; disabled: boolean; onChange: (value: JsonValue) => void }) {
  if (nodeId === "S0") { const route = Array.isArray(draft) ? draft as string[] : []; const add = (item: string) => onChange([...route, item]); return <section><p className="mb-4 text-sm text-ice">A → □ → giro → □□ → giro → B</p><div className="flex flex-wrap gap-2">{[["SI_CAMINO_LIBRE", "Si camino libre"], ["AVANZAR", "Avanzar"], ["DERECHA", "Girar derecha"], ["REPETIR_2", "Repetir 2 avances"], ["IZQUIERDA", "Girar izquierda"]].map(([key, label]) => <button key={key} type="button" disabled={disabled} onClick={() => add(key)} className="rounded-lg border border-[#7B7FE8]/35 bg-[#7B7FE8]/10 px-3 py-2 text-xs text-[#d8d9ff]">{label}</button>)}<button type="button" disabled={disabled} onClick={() => onChange([])} className="rounded-lg border border-line px-3 py-2 text-xs text-muted">Limpiar</button></div><div className="mt-5 min-h-20 rounded-xl border border-dashed border-[#7B7FE8]/30 p-4 font-mono text-sm text-ice">{route.length ? route.join(" → ") : "Selecciona bloques para armar el programa"}</div></section>; }
  if (nodeId === "S2" || nodeId === "S3B") { const values = typeof draft === "object" && draft && !Array.isArray(draft) ? draft as Record<string, string> : {}; const entries = nodeId === "S2" ? [["search", "SEARCH → APPROACH"], ["approach", "APPROACH → INTERACT"], ["interact", "INTERACT → RETURN"], ["return", "RETURN → SEARCH"]] : [["camera", "cámara publica a"], ["detector", "detector publica a"], ["planner", "planner publica a"], ["controlador", "controlador publica a"]]; return <section className="space-y-4">{entries.map(([key, label]) => <label key={key} className="block rounded-xl border border-line bg-night/25 p-4 text-sm text-ice"><span>{label}</span><select disabled={disabled} value={values[key] ?? ""} onChange={(event) => onChange({ ...values, [key]: event.target.value })} className="mt-3 block w-full rounded-lg border border-line bg-[#081923] p-2.5 text-sm text-ink"><option value="">Selecciona una opción…</option>{(nodeId === "S2" ? STATES : ARCH[key as keyof typeof ARCH]).map((option) => <option key={option}>{option}</option>)}</select></label>)}</section>; }
  const scenario = SOFTWARE_SCENARIOS[nodeId]; return <textarea disabled={disabled} value={typeof draft === "string" ? draft : ""} onChange={(event) => onChange(event.target.value)} spellCheck={false} className="min-h-[23rem] w-full resize-y rounded-xl border border-line bg-[#030b12] p-5 font-mono text-sm leading-6 text-[#d8d9ff] outline-none focus:border-[#7B7FE8] disabled:opacity-70" placeholder={scenario.starter ?? "Describe tu propuesta…"} />;
}
function initialProgress(nodeId: SoftwareChallengeNodeId, saved?: NodeChallengeProgress): NodeChallengeProgress { if (saved?.nodeId === nodeId && saved.steps.mission) return saved; const now = Date.now(); const scenario = SOFTWARE_SCENARIOS[nodeId]; const draft: JsonValue = scenario.starter ?? (scenario.type === "route" ? [] : scenario.type === "states" || scenario.type === "architecture" ? {} : ""); return { nodeId, currentStepId: "mission", shuffleSeed: now, startedAt: now, updatedAt: now, completedAt: null, steps: { mission: { draft, attempts: [], revealedHints: 0, totalActiveSeconds: 0, solvedAt: null } }, analytics: { lastEvent: "opened" } }; }
