import type { SoftwareChallengeNodeId } from "./registry";
export interface SoftwareScenario { category: string; title: string; objective: string; hints: string[]; type: "route" | "code" | "states" | "architecture" | "free"; starter?: string; }
export const SOFTWARE_SCENARIOS: Record<SoftwareChallengeNodeId, SoftwareScenario> = {
  S0: { category: "Lógica", title: "Programa la ruta", objective: "Lleva el rover hasta el premio esquivando las cajas y de la manera más eficiente. Ten en cuenta que el rover inicia mirando hacia el este y al usar los bloques de girar, también avanza una casilla.", hints: ["Primero se debe comprobar que es seguro avanzar.", "Llega al premio en el menor número de movimientos posible."], type: "route" },
  S1A: { category: "Python", title: "Código que decide", objective: "Completa decision(distancia): AVANZAR si es mayor que 80 cm, REDUCIR entre 31 y 80 cm y DETENER si es 30 cm o menos.", hints: ["Evalúa primero la distancia más corta.", "Devuelve exactamente los textos solicitados."], type: "code", starter: "def decision(distancia):\n    # Escribe tu lógica aquí\n    pass\n" },
  S1B: { category: "Depuración", title: "Rompe el bug", objective: "Repara velocidad(distancia). Debe detenerse a 30 cm o menos, reducir a 80 cm o menos y avanzar en cualquier otra distancia.", hints: ["Los condicionales se evalúan de arriba hacia abajo.", "No olvides devolver un valor en todos los caminos."], type: "code", starter: "def velocidad(distancia):\n    if distancia <= 80:\n        return \"REDUCIR\"\n    elif distancia <= 30:\n        return \"DETENER\"\n    return \"AVANZAR\"\n" },
  S2: { category: "Máquina de estados", title: "Define las transiciones", objective: "Configura SEARCH → APPROACH → INTERACT → RETURN: buscar una caja, acercarse, tomarla y volver a la base.", hints: ["Cada transición necesita el evento que habilita la siguiente.", "APPROACH termina cuando el objeto está al alcance."], type: "states" },
  S3A: { category: "Mensajes", title: "Haz que los sistemas hablen", objective: "Completa procesar(mensaje): recibe JSON con distance_cm y devuelve STOP (≤30), SLOW (≤80) o GO (>80). Un mensaje inválido devuelve INVALID.", hints: ["Convierte el texto con json.loads.", "Captura JSON inválido con try / except."], type: "code", starter: "import json\n\ndef procesar(mensaje):\n    # devuelve STOP, SLOW, GO o INVALID\n    pass\n" },
  S3B: { category: "Arquitectura ROS 2", title: "Conecta los nodos", objective: "El flujo debe procesar la imagen del sensor visual para extraer obstáculos, calcular la trayectoria óptima y enviar los comandos finales de velocidad al hardware de tracción. (Nota: El nodo de control motriz es el único con acceso directo a los actuadores).", hints: ["Cada nodo debe tener una responsabilidad única.", "Un detector publica objetos, no comandos de motor."], type: "architecture" },
  S4: { category: "Reto libre", title: "Software libre", objective: "Propón una herramienta útil: nodo, controlador, GUI, simulador, visualizador o algoritmo. Explica problema, arquitectura, uso y una prueba.", hints: ["Nombra entradas, salidas y comportamiento esperado.", "Incluye una prueba reproducible y una limitación."], type: "free" },
};
export function evaluateSoftware(nodeId: SoftwareChallengeNodeId, draft: unknown): { correct: boolean; feedback: string } {
  if (nodeId === "S0") { const route = Array.isArray(draft) ? draft : []; const correct = route.join("|") === "SI_CAMINO_LIBRE|AVANZAR|DERECHA|REPETIR_2|IZQUIERDA"; return { correct, feedback: correct ? "Ruta verificada: el rover llega a B sin entrar a la zona bloqueada." : "La secuencia todavía no lleva al rover a B." }; }
  if (nodeId === "S2" || nodeId === "S3B") { const values = draft as Record<string, unknown>; const expected = nodeId === "S2" ? { search: "objeto detectado", approach: "objeto al alcance", interact: "objeto tomado", return: "base detectada" } : { camera: "detector", detector: "planner", planner: "controlador", controlador: "motores" }; const correct = Object.entries(expected).every(([key, value]) => values?.[key] === value); return { correct, feedback: correct ? "Diseño validado: el flujo es coherente y completo." : "Revisa que cada fase conecte con la siguiente correcta." }; }
  if (nodeId === "S4") { const correct = typeof draft === "string" && draft.trim().length >= 220; return { correct, feedback: correct ? "Entrega registrada para revisión humana." : "Describe la propuesta con al menos 220 caracteres." }; }
  const code = typeof draft === "string" ? draft.toLowerCase() : ""; const ordered = nodeId !== "S1B" || (code.indexOf("<= 30") >= 0 && code.indexOf("<= 80") > code.indexOf("<= 30")); const correct = /return/.test(code) && /if/.test(code) && ordered && (nodeId !== "S3A" || (/json\.loads/.test(code) && /except/.test(code))) && (nodeId === "S1B" || (/80/.test(code) && /30/.test(code))); return { correct, feedback: correct ? "Todos los tests simulados pasaron." : "Aún falla algún test. Revisa límites, retornos y casos extremos." };
}
